# Generated by Django 3.1.14 on 2022-11-11 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0009_auto_20221111_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
    ]
